namespace ToggleIt
{
    public static class ModInvariables
    {
        public static readonly int[] Toggles =
        {
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15
        };

        public static readonly string[] ToggleNames =
        {
            "Automatic Info Views",
            "Notification Icons",
            "Road Names",
            "Buildings",
            "Border Lines",
            "Contour Lines",
            "Zoning",
            "Zoning Grids",
            "Zoning Colors",
            "District Zones",
            "District Names",
            "District Icons",
            "Tool Colors",
            "Tool Info",
            "Tool Extra Info",
            "Dark Info Views"
        };

        public static readonly int[] Keymappings =
        {
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70
        };

        public static readonly string[] KeymappingNames =
        {
            "None",
            "LEFT CTRL + A",
            "LEFT CTRL + B",
            "LEFT CTRL + C",
            "LEFT CTRL + D",
            "LEFT CTRL + E",
            "LEFT CTRL + F",
            "LEFT CTRL + G",
            "LEFT CTRL + H",
            "LEFT CTRL + I",
            "LEFT CTRL + J",
            "LEFT CTRL + K",
            "LEFT CTRL + L",
            "LEFT CTRL + M",
            "LEFT CTRL + N",
            "LEFT CTRL + O",
            "LEFT CTRL + P",
            "LEFT CTRL + Q",
            "LEFT CTRL + R",
            "LEFT CTRL + S",
            "LEFT CTRL + T",
            "LEFT CTRL + U",
            "LEFT CTRL + V",
            "LEFT CTRL + W",
            "LEFT CTRL + X",
            "LEFT CTRL + Y",
            "LEFT CTRL + Z",
            "LEFT CTRL + 1",
            "LEFT CTRL + 2",
            "LEFT CTRL + 3",
            "LEFT CTRL + 4",
            "LEFT CTRL + 5",
            "LEFT CTRL + 6",
            "LEFT CTRL + 7",
            "LEFT CTRL + 8",
            "LEFT CTRL + 9",
            "LEFT ALT + A",
            "LEFT ALT + B",
            "LEFT ALT + C",
            "LEFT ALT + D",
            "LEFT ALT + E",
            "LEFT ALT + F",
            "LEFT ALT + G",
            "LEFT ALT + H",
            "LEFT ALT + I",
            "LEFT ALT + J",
            "LEFT ALT + K",
            "LEFT ALT + L",
            "LEFT ALT + M",
            "LEFT ALT + N",
            "LEFT ALT + O",
            "LEFT ALT + P",
            "LEFT ALT + Q",
            "LEFT ALT + R",
            "LEFT ALT + S",
            "LEFT ALT + T",
            "LEFT ALT + U",
            "LEFT ALT + V",
            "LEFT ALT + W",
            "LEFT ALT + X",
            "LEFT ALT + Y",
            "LEFT ALT + Z",
            "LEFT ALT + 1",
            "LEFT ALT + 2",
            "LEFT ALT + 3",
            "LEFT ALT + 4",
            "LEFT ALT + 5",
            "LEFT ALT + 6",
            "LEFT ALT + 7",
            "LEFT ALT + 8",
            "LEFT ALT + 9"
        };
    }
}
